### ISSUE TITLE
usage of internal diseqc-switch

### ISSUE THREAD

**Issue by fkzle** [Jalle19/satip-axe#53] opened 2022-12-23 21:09 UTC
parameter "--free-inputs" of perexg. 

My setup looks like this:
inputs 1-3: external diseqc-switch with Astra 19.2° and Astra 28.5°
Input 4: directly connected to LNB for Hotbird 13°. 

I used the "free-inputs" parameter to configure this behaviour. 

my client (VDR) was able to receive all positions. 
After update to your branch, the paramater is not working anymore. 
The "--virtual-diseqc" apparently does something else.  I am not receiving the 13° satellite anymore. 
I can sort out that also with a properly crafted http URL (with all sat parameters correctly set), it is not possible to receive this position. 

How can i achieve this functionality with the stock minisatip? How can i leverage the power of the internal diseqc-switch of the digibit R1?

**Comment by Jalle19** [comment] 2022-12-24 06:32
What values did you use for --virtual-diseqc before?

**Comment by fkzle** [comment] 2022-12-24 09:30
I used the following:
0:0:0,1:0:1,0:1:0,1:1:1,0:2:0,1:2:1,2:3:0

**Comment by Jalle19** [comment] 2022-12-24 13:08
So the only thing not working anymore is Hotbird on input 4?

**Comment by fkzle** [comment] 2022-12-24 17:16
Exactly.
Inputs 1-3 with both positions are working.

**Comment by fkzle** [comment] 2022-12-25 11:13
In the screenshot, i tried to watch "kabelio info" on hotbird (11526MHz H, PIDs: 4531 and 4532). 
![image](https://user-images.githubusercontent.com/96884764/209465728-203c33c8-f12b-4e41-b71f-beabe9425378.png)

It looks like the mapping is affecting the tuner, not the input of the switch. 
(Tuner 3 still uses LNB1)

**Comment by Jalle19** [comment] 2022-12-25 17:00
I'll get back to you after Christmas. I believe you need to use the -S switch as well to tell minisatip that src=3 should use LNB4.

**Comment by fkzle** [comment] 2022-12-25 21:18
I am not completely sure how this should help. Every input has its own cable to the (external) diseqc-switch, none of them are linked together.

**Comment by Jalle19** [comment] 2022-12-26 07:42
> This feature is used by FBC receivers and AXE to specify the source input of the adapter

**Comment by fkzle** [comment] 2023-01-03 18:36
I tried your suggestion, but you are correct, this is rather unintuitive (and sadly also badly documented).

I tried "-S 0:0,1:1,2:2,3:3" and expecting that a certain tuner should use its corresponding input (tuner 2 using input 2). This seems not to be the case. 

In addition, i got a lot of  "connect failed" on my satip-client. (though this may be unrelated)

![2023-01-03_19-32](https://user-images.githubusercontent.com/96884764/210419528-15371e94-803d-44e2-ac5d-ac2d4bb70899.png)

**Comment by Jalle19** [comment] 2023-01-04 08:28
Personally I have one Unicable LNB connected to input 1 and another Unicable LNB connected to input 4, and I have it configured so that the first three tuners use input 1 while the fourth tuner uses input 4. This is done with `-S 0-2:0,3:3 -A 0:0:0,0:1:0,0:2:0,1:3:1`.

Do you have physical cables attached to each of your inputs, or only inputs 1 and 4? :thinking:

**Comment by fkzle** [comment] 2023-01-04 15:15
Exactly. Input 1-3 can be used independently, since they are all connected to the external diseqc-switch. 


                                                                    Digibit R1
                                  Diseqc-Switch         _________
[LNB 19.2° East ] -------- #### ------------|  In 1   |
                                         ####                 |             |
                                         #### -------------|  In 2    |
                                         ####                 |             |
[LNB 28.5° East ] -------- #### -------------|  In 3    |
                                                                    |              |
[LNB 13° East] ----------------------------------| In 4     |
                                                                     |_______|

**Comment by Jalle19** [comment] 2023-01-05 19:59
Can you try `-A 0:0:0,1:0:1,0:1:0,1:1:1,0:2:0,1:2:1,2:3:0 -S 3:3`?

**Comment by Jalle19** [comment] 2023-01-05 20:03
You could also try `-A 0:0:0,1:0:1,0:1:0,1:1:1,0:2:0,1:2:1,2:3:0 -S 0:0,1:1,2:2,3:3`

**Comment by fkzle** [comment] 2023-01-05 20:37
I already tested the latter 2 days ago. See [Post](https://github.com/Jalle19/satip-axe/issues/53#issuecomment-1370100724)

I will test the other tomorrow, although i doubt that this will help...

**Comment by Jalle19** [comment] 2023-01-05 20:56
I was unsure if you tested with both -A and -S.

**Comment by fkzle** [comment] 2023-01-06 18:46
This did not work as well. 

![image](https://user-images.githubusercontent.com/96884764/211076871-178894ca-0f98-402f-99a9-3c2407493759.png)

Minisatip cannot be convinced to use input 4 if position 2 is requested. 
In addition: if your suggestions with parameter -S would work, this still would be a regression compared to the old minisatip. Before it was possible to watch >1 program on different tuners, if they all are in the same Band. By fixing lnb4 to tuner4, this is not possible anymore.

**Comment by fkzle** [comment] 2023-01-06 18:50
Do you have extended knowledge about the internals of the digibit R1? 
Is the internal switch also addressed via diseqc? or is this done from the axe utils via some internal bus, e.g. i2c?

If it is diseqc, maybe something with -d or -0 could do the magic? If the internal switch is addressed via diseqc, is it committed or uncommitted?

**Comment by Jalle19** [comment] 2023-01-07 06:17
I honestly don't know, sorry.

@catalinii do you know what parameters should be used here?

**Comment by catalinii** [comment] 2023-01-07 17:29
I think 
-A 0:0:0,1:0:1,0:1:0,1:1:1,0:2:0,1:2:1,2:3:0 -S 0:0,1:1,2:2,3:3 should work.

But generally you need a hotbird URL that has src=3 in it and if it does not work upload the logs with 
'-l axe,http -f'

**Comment by fkzle** [comment] 2023-01-07 19:13
@catalinii This is exactly what i tried.
Somehow, the URL with src=3 is internally rewritten to src=1. But Tuner 4 is used. 

If i look at wireshark, src=3 is requested by VDR, but if i then look into the minisatip-webfrontend, i see that tuner 4 is used with the correct frequency and the PIDs requested, but if i look at the link in the web-if, there is src=1 set. 

I will try to upload logs later.

**Comment by Jalle19** [comment] 2023-03-24 16:23
@fkzle did you get it to work?

**Comment by fkzle** [comment] 2023-03-24 19:21
nope. 
after trying a lot of settings and command line parameters, and also after trying to understand the sourcecode, i gave up and am using the old version from perexg.

**Comment by Jalle19** [comment] 2023-03-24 20:47
Could very well be a regression. Closing this though since it doesn't seem to be an issue with the firmware per se.

**Closed by Jalle19** 2023-03-24 20:47 UTC
